# Generated by Django 5.2.12 on 2026-03-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PkceSession',
            fields=[
                ('state', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('code_verifier', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='gateway_pkc_expires_f65622_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenExchangeCode',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('token_encrypted_b64', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='gateway_tok_expires_97a319_idx'), models.Index(fields=['consumed_at'], name='gateway_tok_consume_6186b1_idx')],
            },
        ),
    ]
